name = 'Vortisil'
license = 'GPL-3.0-or-later'
licenselink = 'https://github.com/khitezza/vortisil/LICENSE'
description = 'A fast, minimal, and restrained Hugo theme.'
homepage = 'https://github.com/khitezza/vortisil'
tags = ['simple', 'clean']
features = ['blog', 'novels']
min_version = "0.142.0"

[author]
  name = 'Hao Wu'
  homepage = 'https://khitezza.com'
