# 部署 Hugo 站点到 GitHub Pages
name: Deploy Hugo site to Pages

on:
  push:
    branches: ["trunk"]  # 确保分支名称和你仓库的默认分支一致
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      HUGO_VERSION: 0.143.1  # 你可以修改为最新 Hugo 版本
    steps:
      - name: 安装 Hugo CLI
        run: |
          wget -O ${{ runner.temp }}/hugo.deb https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_linux-amd64.deb \
          && sudo dpkg -i ${{ runner.temp }}/hugo.deb          
      - name: 安装 Dart Sass（如果你的 Hugo 主题需要 SCSS）
        run: sudo snap install dart-sass
      - name: 拉取仓库代码
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: 配置 GitHub Pages
        id: pages
        uses: actions/configure-pages@v5
      - name: 安装 Node.js 依赖（如果有）
        run: "[[ -f package-lock.json || -f npm-shrinkwrap.json ]] && npm ci || true"
      - name: 使用 Hugo 构建网站
        env:
          HUGO_CACHEDIR: ${{ runner.temp }}/hugo_cache
          HUGO_ENVIRONMENT: production
        run: |
          hugo \
            --minify \
            --baseURL "${{ steps.pages.outputs.base_url }}/"          
      - name: 上传网站文件
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: 部署到 GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
